// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJX7eBbuaAngMZP5w3FyIH0lA1vQEAfQE',
    appId: '1:330379322234:web:5c8e3e3773c87ceb366cc3',
    messagingSenderId: '330379322234',
    projectId: 'communitycart-99510',
    authDomain: 'communitycart-99510.firebaseapp.com',
    storageBucket: 'communitycart-99510.firebasestorage.app',
    measurementId: 'G-HH6X62YK7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe6eOTNsfi9SqGjZavfwuyjUUrYC_yBGw',
    appId: '1:330379322234:android:0f1e5fd02b06d67d366cc3',
    messagingSenderId: '330379322234',
    projectId: 'communitycart-99510',
    storageBucket: 'communitycart-99510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDegwFX18QTQWSd0WRHKf1fWfNdxzLvxTw',
    appId: '1:330379322234:ios:14c688c07f48fec3366cc3',
    messagingSenderId: '330379322234',
    projectId: 'communitycart-99510',
    storageBucket: 'communitycart-99510.firebasestorage.app',
    iosBundleId: 'com.example.cart',
  );
}
